webhook_url = ENV['DISCORD_WEBHOOK_URL']

desc "Create build for testing"
lane :build_for_testing do
  cocoapods

  scan(
    build_for_testing: true
  )
end

desc "Run tests on build"
lane :run_tests do
  scan(
    test_without_building: true
  )
end

desc "Send notification to discord"
lane :send_discord_notification do
  discord_notifier(
    webhook_url: webhook_url,
    title: "Tinkoff Chat",
    description: "Build finished"
  )
end

desc "Create build and run tests"
lane :build_and_test do
  # scan
  build_for_testing
  run_tests
  
  send_discord_notification
end
