
desc "Create build for testing"
lane :build_for_testing do
  cocoapods

  scan(
    build_for_testing: true
  )
end

desc "Run tests on build"
lane :run_tests do
  scan(
    test_without_building: true
  )
end

webhook_url = ENV['DISCORD_WEBHOOK_URL']

desc "Create build and run tests"
lane :build_and_test do
  # scan
  build_for_testing
  run_tests
end
